### ISSUE TITLE
Typedefinition lacks Promise definition

### ISSUE THREAD

**Issue by chebum** [spacejack/mithril.d.ts#12]
Hi,

I noticed that mithril.d.ts relies on Promise definition provided by system definition files. Unfortunately, this breaks compilation if project targets ES5. With this target no Promise definition is provided and the compilation fails with `error TS2693: 'Promise' only refers to a type, but is being used as a value here.` error.

The problem can be solved in tsconfig.json with lib option as below:
```
{
  "compilerOptions": {
    ...
    "target": "ES5",
    "lib": [
      "dom",
      "es2015.promise",
      "es5",
      "scripthost"
    ]
    ...
  },
  ...
}
```

"dom", "es5" and "scripthost" are default values for the lib when target is "ES5". Adding  "es2015.promise" solves compilation errors. 

I believe a notice about that change in readme.md will benefit newcomers trying to use Mithril with TypeScript.

**Comment by andraaspar** [comment]
Thanks for reporting. I have added a note to the Install section.
