### ISSUE TITLE
Typescript definition: RouterResolver render type error

### ISSUE THREAD

**Issue by seoyeongB** [spacejack/mithril.d.ts#19]
I re-report this issue (https://github.com/lhorie/mithril.js/issues/1805)
Thank you!

My problem,

e.g) test.com/test/:test_number
```
interface MyAttrs {
  test_number: string;
}

class MyState {
  test: Test;
}

const TestRouteResolver: m.RouteResolver<MyState, MyAttrs> = {
  onmatch(args, requestedPath) {
    ...
  },
  render(vnode) {
    vnode.key = vnode.attrs.test_number; // <- compile error!
    return vnode;
  }
};
```

For me, it seems like definition of vnode in render function should be fixed.

While defining type of vnode interface, ‘Attrs’ comes first and ‘state’ follows.
However, order of vnode type in render function is ‘State, Params’

I think order of vnode type in render function be changed as defined in vnode interface, that is ‘Params, State’.

current code is..
```
render?(this: State, vnode: Vnode<State, Params>): Children; // vnode: Vnode<Params, State>?

```
Vnode interface is defined..
```
interface Vnode<Attrs, State extends Lifecycle<Attrs, State>>
```

**Comment by spacejack** [comment]
@seoyeongB Yes, this looks like a mistake.

@andraaspar, @isiahmeadows any objection to making this change?

**Comment by andraaspar** [comment]
It should be fixed alright. Please go ahead.

**Comment by spacejack** [comment]
Hi everyone, sorry for the delay, it was a busy week and I needed to do some testing to better understand the types in the RouteResolver.

Please see [these changes](https://github.com/spacejack/mithril.d.ts/compare/route-resolver-fix)

[This new test](https://github.com/spacejack/mithril.d.ts/blob/route-resolver-fix/test/test-route.ts#L17-L48) should demonstrate correct usage. ~~We only really need the Attrs generic type. The vnode state object is always empty and~~ `this` is set to the type of the RouteResolver object; if you add additional properties to it they will be available in `onmatch` and `render`.

@isiahmeadows if you can take a look it would be appreciated.

@seoyeongB can you give this a try in your own project and see that it works for you? You can install with `npm install -D github:spacejack/mithril.d.ts#route-resolver-fix`

**Comment by spacejack** [comment]
Sorry, I was wrong, the vnode.state does have properties in the route resolver if you add them in the component. I've made changes to reflect that.

**Comment by seoyeongB** [comment]
@spacejack It works well! 👍

**Comment by spacejack** [comment]
Merged in DefinitelyTyped
