### ISSUE TITLE
ClassComponent lifecycle method vnode types

### ISSUE THREAD

**Issue by vrimar** [spacejack/mithril.d.ts#20]
Any reason as to why the lifecycle method vnode types for ClassComponents are `m.Vnode/m.VnodeDOM` and not `m.CVnode/m.CVnodeDOM` ? 

I can submit a PR if need be.

**Comment by spacejack** [comment]
The reason being that `vnode.state` should have your class properties on it.

That said... I notice that the `view` vnode type is `CVnode<A>`, and should be `Vnode<A, this>` :/

But Typescript can't infer these types in your class methods, so you end up having to write them out anyway.

**Comment by vrimar** [comment]
Ah, I see. I write my components like: 
```
interface IAttrs {
 // ...attrs
}

class Component<A> implements m.ClassComponent<A> {
	prop: boolean = false;
	someOtherProp: number = 0;

	oninit(vnode: m.CVnode<IAttrs>) {
		this.prop = true;
		this.someOtherProp = 1;
	}

	view() {}
}
```
so I don't need the type safety on `vnode.state` but it definitely should be there.

**Comment by spacejack** [comment]
Yes, if you're using classes, you probably don't use `vnode.state`.

Once [this feature](https://github.com/lhorie/mithril.js/pull/1796) is released however, there may be more use for it.

Anyway thanks, I'll fix the `view` signature.

**Comment by vrimar** [comment]
Ok, sounds good.

**Comment by spacejack** [comment]
Fix in [this branch](https://github.com/spacejack/mithril.d.ts/tree/class-view-vnode-type).
