### ISSUE TITLE
m.request.config type

### ISSUE THREAD

**Issue by oldrich-s** [spacejack/mithril.d.ts#25]
`config` in `request` should probably look something like this:

```
config?(xhr: XMLHttpRequest, args: RequestOptions<T>): XMLHttpRequest | void;
```

instead of this

```
config?(xhr: XMLHttpRequest): any;
```

See:

```
if (typeof args.config === "function") xhr = args.config(xhr, args) || xhr
```

**Comment by spacejack** [comment]
@czb yes, that looks right to me, thanks. Do you want to create a PR for DefinitelyTyped? Otherwise I can do it.

**Comment by oldrich-s** [comment]
Shall I make PR to this repo or directly to DefinitelyTyped? I have tried to clone DefinitelyTyped before to make PR but after a couple of hours I gave up :)

**Comment by spacejack** [comment]
It should go to DefinitelyTyped (this repo is a bit out of sync right now... I need to clean that up. It's mostly for experimentation and discussion.)

Anyway I can make the DefinitelyTyped PR, probably today.

**Comment by spacejack** [comment]
PR submitted.

**Comment by oldrich-s** [comment]
thanks 👍 

BTW: in the source code, the function accepts a second parameter `args`. Any reason why it is not reflected in the `d.ts` file?

**Comment by spacejack** [comment]
Sorry, I totally missed your last comment and did overlook the additional parameter. I've made a new PR now to include it.
