### ISSUE TITLE
Support for JSX out of the box?

### ISSUE THREAD

**Issue by ketan** [spacejack/mithril.d.ts#31]
Hi —

I was wondering if there'd be interest in adding out-of-the-box support for JSX. I'm happy to submit some initial code to get this going and improve support over time.

Thanks and let me know.

**Comment by andraaspar** [comment]
@ketan Full support for TSX is not possible with type declarations alone. A base class is required. Have a look at: https://www.npmjs.com/package/mithril-tsx-component

**Comment by ketan** [comment]
Yes — I'm familiar with that particular project. Thank you for writing it. I'll submit any PRs I have to the tsx-component project instead.

Closing this issue.

**Comment by spacejack** [comment]
@andraaspar I've updated the readme with a link to your library.

I also added some notes about using more modern `import` style and the `esModuleInterop` flag.
