### ISSUE TITLE
Arguments when using m.route.link in <a> lifecycle method

### ISSUE THREAD

**Issue by chocolatkey** [spacejack/mithril.d.ts#35]
The mithril [link docs](https://mithril.js.org/route.html#mroutelink) show this method of using `m.route.link`: 

```js
m("a[href=/]", {oncreate: m.route.link({replace: true})})
```

however `m.route.link` only accepts the type `Vnode<any, any>`.

```
[ts]
Argument of type '{ replace: boolean; }' is not assignable to parameter of type 'Vnode<any, any>'.
  Object literal may only specify known properties, and 'replace' does not exist in type 'Vnode<any, any>'. [2345]
```

How should this method be used in TS?

**Comment by spacejack** [comment]
Sorry for the wait. Submitted in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32504

**Comment by spacejack** [comment]
Merged to DT.
