### ISSUE TITLE
Add this to types repo

### ISSUE THREAD

**Issue by winksaville** [spacejack/mithril.d.ts#6]
Hello, I see in [this issue](https://github.com/lhorie/mithril.js/issues/1402) that you suggested adding this directly to mithril.js, too bad that didn't happen :(

But I see you suggested adding it to DT, but I'd like to suggest instead of that, or maybe in addition to that, you add it to [types](https://github.com/types) so `typings` can be used for managing.

**Comment by spacejack** [comment]
Hi - this is getting merged into the mithril.js repo actually. Should be included in the next release.

**Comment by winksaville** [comment]
Nice!!!!
